# Generated by Django 2.2.5 on 2019-09-12 18:36

import authUsers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUsers', '0002_customuser_twilioidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='AuthyIdentity',
            field=models.CharField(default=0, max_length=10, null=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twilioIdentity',
            field=models.IntegerField(default=authUsers.models.CustomUser.number, unique=True),
        ),
    ]
