# Generated by Django 2.2.4 on 2019-09-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUsers', '0005_remove_customuser_authyidentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='twilioIdentity',
        ),
    ]
